In [2]:
import torch

In [14]:
def activation(x):

    return 1/(1 + torch.exp(-x))

In [15]:
torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))

In [22]:
y

tensor([[0.6104, 0.5095, 0.8153, 0.5408, 0.0740]])

NameError: name 'tensor' is not defined

In [39]:
w = weights.reshape(5, 1)
q = weights.view(5, 1)
print(q)
w

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])


tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [41]:
torch.matmul(features, w)


tensor([[-1.9796]])

In [42]:
torch.matmul(features, q)

tensor([[-1.9796]])

In [44]:
y = activation(torch.sum((features * weights) +  bias))
z = activation(torch.sum(torch.matmul(features, w) + bias))

In [52]:
z = activation(torch.sum(torch.mm(features, w) + bias))

In [53]:
z

tensor([[0.6104, 0.5095, 0.8153, 0.5408, 0.0740]])

In [54]:
y

tensor([[0.6104, 0.5095, 0.8153, 0.5408, 0.0740]])

In [59]:
torch.manual_seed(7)
feature = torch.randn((1,3))
n_input = feature.shape[1]
hidden_layer = 2
n_output = 1


In [60]:
W1 = torch.randn(n_input, hidden_layer)
W2 = torch.randn(hidden_layer, n_output)

In [61]:
B1 = torch.randn(1, hidden_layer)
B2 = torch.randn(1, n_output)

In [62]:
n_input


3

In [66]:
h = activation(torch.sum((feature * W1) +  B1))
o = activation(torch.sum(h * feature + B2))

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [70]:
W1

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])

In [78]:
feature

tensor([[-0.1468,  0.7861,  0.9468]])

In [79]:
import numpy as np

In [99]:
def cross_entropy(P, Y):
    Y = np.float_(Y)
    P = np.float_(P)
    return -np.sum(Y * np.log(P) + (1-Y) * (np.log(1-P)))

In [104]:
cross_entropy(P= [0.4, 0.6, 0.1, 0.5], Y = [1, 0, 1, 1])

4.828313737302301